INSERT INTO `api_listofpriority` (`LOPID`, `expenseTitle`, `category`, `is_active`) VALUES
(1, 'TRAVELLING EXPENSE', 'travel', 1),
(2, 'TRAINING EXPENSE', 'training', 1),
(3, 'TRAINING EXPENSES (GAD / INSET)', 'training', 1),
(4, 'TRAINING EXPENSES (LAC SESSION)', 'training', 1),
(5, 'OFFICE / OTHER SUPPLIES EXPENSE (DBM)', 'supplies', 1),
(6, 'OFFICE / OTHER SUPPLIES EXPENSE (OUTSIDE DBM)', 'supplies', 1),
(7, 'ELECTRICITY EXPENSE', 'utilities', 1),
(8, 'WATER EXPENSE', 'utilities', 1),
(9, 'INTERNET EXPENSE (DSL / GLOBE)', 'communication', 1),
(10, 'INTERNET EXPENSE (POCKET WIFI)', 'communication', 1),
(11, 'MOBILE EXPENSE', 'communication', 1),
(12, 'SECURITY SERVICES (TANOD / NON-AGENCY)', 'services', 1),
(13, 'SECURITY SERVICES (AGENCY)', 'services', 1),
(14, 'JANITORIAL SERVICES (NON-AGENCY)', 'services', 1),
(15, 'REPAIR AND MAINTENANCE - B/SB/OE/FF/MV/OPPE', 'maintenance', 1),
(16, 'FIDELITY BOND PREMIUM', 'taxes', 1),
(17, 'LABOR AND WAGES', 'labor', 1),
(18, 'REPRESENTATION EXPENSE', 'other_maintenance', 1),
(19, 'FUEL, OIL, AND LUBRICANTS EXPENSE', 'other_maintenance', 1),
(20, 'TRANSPORTATION AND DELIVERY EXPENSE (HAULING)', 'other_maintenance', 1),
(21, 'DRUGS AND MEDICINES / MEDICAL / DENTAL / LAB SUPPLIES', 'other_maintenance', 1),
(22, 'FOOD SUPPLIES EXPENSE (FEEDING)', 'other_maintenance', 1);