INSERT INTO `api_requirement` (`requirementID`, `requirementTitle`, `is_required`, `is_active`) VALUES
(1, 'Abstract of Quotation (AOQ)', 1, 1),
(2, 'Accomplishment Report', 1, 1),
(3, 'Acknowledgement Receipt (AR)', 1, 1),
(4, 'Agency Procurement Request (APR)', 1, 1),
(5, 'Approved Activity Request Form', 1, 1),
(6, 'Approved Authority to Travel / Locator Slip', 1, 1),
(7, 'Approved Certificate of Travel Completed', 1, 1),
(8, 'Approved Itinerary of Travel', 1, 1),
(9, 'Attendance', 1, 1),
(10, 'Authority to Claim (copy)', 1, 1),
(11, 'BAC Resolution', 1, 1),
(12, 'Barangay Certificate (for initial submission)', 1, 1),
(13, 'BIR Forms 2306 / 2307', 1, 1),
(14, 'Certification of Non-Availability of Stocks', 1, 1),
(15, 'Certification of Official Business (OB) calls', 1, 1),
(16, 'Certification of Stock Availability and Price Quotation', 1, 1),
(17, 'Certification: not recipient of sim card / other allowances for communication', 1, 1),
(18, 'COA Circ1 - COENRR/ Memorandum', 1, 1),
(19, 'Collection Receipt (CR)', 1, 1),
(20, 'Confirmation of Bond', 1, 1),
(21, 'Contract of Service / MOA', 1, 1),
(22, 'Daily Menu of food to be served', 1, 1),
(23, 'Daily Time Record (DTR)', 1, 1),
(24, 'Delivery Receipt (DR) / Charge Invoice (CI)', 1, 1),
(25, 'Detailed Meal Plan', 1, 1),
(26, 'Disbursement Voucher (DV) / optional', 0, 1),
(27, 'Disbursement Voucher (for tax withheld) / optional', 0, 1),
(28, 'GAD Plan and Budget', 1, 1),
(29, 'Inspection and Acceptance Report (IAR)', 1, 1),
(30, 'Inventory Custodian Slip (if applicable)', 0, 1),
(31, 'List of Bondable Official', 1, 1),
(32, 'Memorandum', 1, 1),
(33, 'Menu of Food / Snacks', 1, 1),
(34, 'Narrative Report', 1, 1),
(35, 'Official Receipt (OR)', 1, 1),
(36, 'Official Receipt (OR) / Acknowledgement Receipt (AR)', 1, 1),
(37, 'Original Copy of Certificate of Appearance (CA)', 1, 1),
(38, 'Original copy of Official Receipt (OR)', 1, 1),
(39, 'Payroll (multiple laborer)', 1, 1),
(40, 'Payroll (multiple recipient)', 1, 1),
(41, 'Payment Slip', 1, 1),
(42, 'Permit to Conduct / Approved Request', 1, 1),
(43, 'PhilGEPS Certification / Registration', 1, 1),
(44, 'Photocopy of check issued', 1, 1),
(45, 'Photocopy of valid ID / CTC', 1, 1),
(46, 'Pictures', 1, 1),
(47, 'Pictures (Before - During - After)', 1, 1),
(48, 'Pre-Repair Inspection Report', 1, 1),
(49, 'Program', 1, 1),
(50, 'Program / Training Matrix', 1, 1),
(51, 'Program of Works / Job Order', 1, 1),
(52, 'Proof of receipt of items (signed by authorized recipients)', 1, 1),
(53, 'Purchase Order (PO)', 1, 1),
(54, 'Purchase Request (PR)', 1, 1),
(55, 'Request for Payment', 1, 1),
(56, 'Request for Quotation (RFQ)', 1, 1),
(57, 'Requisition and Issue Slip (RIS)', 1, 1),
(58, 'SBFP Form 1', 1, 1),
(59, 'SBFP Form 4', 1, 1),
(60, 'Sales Invoice (SI)', 1, 1),
(61, 'Signed list of recipients', 1, 1),
(62, 'Statement of Account (SOA)', 1, 1),
(63, 'Tickets (if any)', 0, 1),
(64, 'Trip Ticket (for people transported)', 1, 1);