INSERT INTO `api_schooldistrict` (`districtId`, `districtName`, `municipality`, `legislativeDistrict`, `is_active`) VALUES
(3, 'Agoo East', 'AGOO', '2nd District', 1),
(4, 'Agoo West', 'AGOO', '2nd District', 1),
(5, 'Luna I', 'LUNA', '1st District', 1),
(6, 'Luna II', 'LUNA', '1st District', 1),
(7, 'Bauang North', 'BAUANG', '2nd District', 1),
(8, 'Bauang South', 'BAUANG', '2nd District', 1),
(9, 'Aringay', 'ARINGAY', '2nd District', 1),
(10, 'Bacnotan', 'BACNOTAN', '1st District', 1),
(11, 'Bagulin', 'BAGULIN', '2nd District', 1),
(12, 'Balaoan', 'BALAOAN', '1st District', 1),
(13, 'Bangar', 'BANGAR', '1st District', 1),
(14, 'Burgos', 'BURGOS', '2nd District', 1),
(15, 'Caba', 'CABA', '2nd District', 1),
(16, 'Naguilian', 'NAGUILIAN', '2nd District', 1),
(17, 'Rosario', 'ROSARIO', '2nd District', 1),
(18, 'Pugo', 'PUGO', '2nd District', 1),
(19, 'San Gabriel', 'SAN GABRIEL', '1st District', 1),
(20, 'San Juan', 'SAN JUAN', '1st District', 1),
(21, 'Santo Tomas', 'SANTO TOMAS', '2nd District', 1),
(22, 'Santol', 'SANTOL', '1st District', 1),
(23, 'Sudipen', 'SUDIPEN', '1st District', 1),
(24, 'Tubao', 'TUBAO', '2nd District', 1);