# Generated by Django 5.1.7 on 2025-07-09 14:24

import api.models
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalLiquidationManagement',
            fields=[
                ('LiquidationID', models.CharField(db_index=True, default=api.models.generate_liquidation_id, editable=False, max_length=10)),
                ('refund', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rejection_comment', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review_district', 'Under Review (District)'), ('under_review_division', 'Under Review (Division)'), ('resubmit', 'Needs Revision'), ('approved_district', 'Approved by District'), ('liquidated', 'Liquidated')], default='draft', max_length=30)),
                ('reviewed_at_district', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at_division', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('date_districtApproved', models.DateField(blank=True, null=True)),
                ('date_liquidated', models.DateField(blank=True, null=True)),
                ('remaining_days', models.IntegerField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.requestmanagement')),
                ('reviewed_by_district', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by_division', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical liquidation management',
                'verbose_name_plural': 'historical liquidation managements',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRequestManagement',
            fields=[
                ('request_id', models.CharField(db_index=True, default=api.models.generate_request_id, editable=False, max_length=10)),
                ('request_monthyear', models.CharField(blank=True, max_length=7, null=True)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending'), ('downloaded', 'Downloaded'), ('unliquidated', 'Unliquidated'), ('liquidated', 'Liquidated'), ('advanced', 'Advanced')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('last_reminder_sent', models.DateField(blank=True, null=True)),
                ('demand_letter_sent', models.BooleanField(default=False)),
                ('demand_letter_date', models.DateField(blank=True, null=True)),
                ('date_approved', models.DateField(blank=True, null=True)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_comment', models.TextField(blank=True, null=True)),
                ('rejection_date', models.DateField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical request management',
                'verbose_name_plural': 'historical request managements',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
