# Generated by Django 5.1.7 on 2025-09-29 13:31

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='max_budget',
        ),
        migrations.CreateModel(
            name='HistoricalBudgetAllocation',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('year', models.PositiveIntegerField(help_text='Year for this budget allocation (e.g., 2024)')),
                ('yearly_budget', models.DecimalField(decimal_places=2, help_text='Total yearly budget allocated to the school', max_digits=15)),
                ('monthly_budget', models.DecimalField(decimal_places=2, help_text='Monthly budget (yearly_budget / 12), calculated automatically', max_digits=15)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.school')),
            ],
            options={
                'verbose_name': 'historical budget allocation',
                'verbose_name_plural': 'historical budget allocations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='BudgetAllocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField(help_text='Year for this budget allocation (e.g., 2024)')),
                ('yearly_budget', models.DecimalField(decimal_places=2, help_text='Total yearly budget allocated to the school', max_digits=15)),
                ('monthly_budget', models.DecimalField(decimal_places=2, help_text='Monthly budget (yearly_budget / 12), calculated automatically', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_budget_allocations', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_allocations', to='api.school')),
            ],
            options={
                'ordering': ['-year', 'school__schoolName'],
                'unique_together': {('school', 'year')},
            },
        ),
    ]
