# Generated by Django 5.2.6 on 2025-09-28 20:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidationdocument',
            name='is_resubmission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='liquidationdocument',
            name='resubmission_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document_file', models.FileField(upload_to='liquidation_documents/versions/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('rejected', 'Rejected'), ('superseded', 'Superseded')], default='rejected', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer_comment', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('original_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='api.liquidationdocument')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_document_versions', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_document_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version_number'],
                'indexes': [models.Index(fields=['original_document', 'version_number'], name='api_documen_origina_051b0d_idx')],
            },
        ),
    ]
