# Generated by Django 5.1.7 on 2025-09-16 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalliquidationmanagement',
            name='date_liquidatorApproved',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalliquidationmanagement',
            name='date_submitted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalliquidationmanagement',
            name='reviewed_at_accountant',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalliquidationmanagement',
            name='reviewed_at_liquidator',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalliquidationmanagement',
            name='reviewed_by_accountant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalliquidationmanagement',
            name='reviewed_by_liquidator',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='liquidationmanagement',
            name='date_liquidatorApproved',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liquidationmanagement',
            name='date_submitted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liquidationmanagement',
            name='reviewed_at_accountant',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liquidationmanagement',
            name='reviewed_at_liquidator',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liquidationmanagement',
            name='reviewed_by_accountant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accountant_reviewed_liquidations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='liquidationmanagement',
            name='reviewed_by_liquidator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liquidator_reviewed_liquidations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalliquidationmanagement',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review_district', 'Under Review (District)'), ('under_review_liquidator', 'Under Review (Liquidator)'), ('under_review_division', 'Under Review (Division)'), ('under_review_accountant', 'Under Review (Accountant)'), ('resubmit', 'Needs Revision'), ('approved_district', 'Approved by District'), ('approved_division', 'Approved by Division'), ('liquidated', 'Liquidated')], default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='liquidationmanagement',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review_district', 'Under Review (District)'), ('under_review_liquidator', 'Under Review (Liquidator)'), ('under_review_division', 'Under Review (Division)'), ('under_review_accountant', 'Under Review (Accountant)'), ('resubmit', 'Needs Revision'), ('approved_district', 'Approved by District'), ('approved_division', 'Approved by Division'), ('liquidated', 'Liquidated')], default='draft', max_length=30),
        ),
    ]
