# Generated by Django 5.2 on 2025-07-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquidationmanagement',
            name='comment_id',
        ),
        migrations.AddField(
            model_name='liquidationmanagement',
            name='rejection_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
