# Generated by Django 5.2 on 2025-06-21 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofpriority',
            name='requirements',
            field=models.ManyToManyField(related_name='priority_requirement', through='api.PriorityRequirement', to='api.requirement'),
        ),
    ]
