# Generated by Django 5.2.3 on 2025-08-21 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='school_district',
            field=models.ForeignKey(blank=True, help_text='District assignment (only for district administrative assistants)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district_users', to='api.schooldistrict'),
        ),
    ]
