# Generated by Django 5.2 on 2025-09-26 01:31

import api.json_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='new_values',
            field=models.JSONField(blank=True, encoder=api.json_utils.DecimalJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='old_values',
            field=models.JSONField(blank=True, encoder=api.json_utils.DecimalJSONEncoder, null=True),
        ),
    ]
