# Generated by Django 5.2 on 2025-06-12 02:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('school_head', 'School Head'), ('school_admin', 'School Administrative Assistant'), ('district_admin', 'District Administrative Assistant'), ('superintendent', 'Division Superintendent'), ('liquidator', 'Liquidator'), ('accountant', 'Division Accountant')], default='school_admin', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
