# Generated by Django 5.1.7 on 2025-06-26 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmanagement',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending'), ('downloaded', 'Downloaded'), ('liquidated', 'Liquidated')], default='pending', max_length=20),
        ),
    ]
