# Generated by Django 5.2.3 on 2025-06-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listofpriority',
            old_name='requirements',
            new_name='requirementss',
        ),
        migrations.AddField(
            model_name='listofpriority',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
