# Generated by Django 5.2 on 2025-07-14 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='school_district',
            field=models.ForeignKey(blank=True, help_text='District assignment (only for district administrative assistants)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district_users', to='api.schooldistrict'),
        ),
    ]
