# Generated by Django 5.2 on 2025-06-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='id',
        ),
        migrations.AlterField(
            model_name='school',
            name='schoolId',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
