# Generated by Django 5.2 on 2025-06-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='max_budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Maximum Budget'),
        ),
    ]
