# Generated by Django 5.2.3 on 2025-06-22 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidationmanagement',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('resubmit', 'Resubmit'), ('completed', 'Completed'), ('unliquidated', 'Unliquidated')], default='ongoing', max_length=20),
        ),
        migrations.AlterField(
            model_name='requestmanagement',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending'), ('downloaded', 'Downloaded')], default='pending', max_length=20),
        ),
    ]
