# Generated by Django 5.2.3 on 2025-06-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listofpriority',
            name='category',
            field=models.CharField(choices=[('travel', 'Travel-Related Expenses'), ('communication', 'Communication & Utilities'), ('office', 'Office & Supplies Expenses'), ('services', 'Services & Maintenance'), ('medical', 'Medical & Food Supplies'), ('misc', 'Miscellaneous Expenses')], default='misc', max_length=30),
        ),
    ]
