# Generated by Django 5.1.7 on 2025-06-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmanagement',
            name='request_month',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
