# Generated by Django 5.2.3 on 2025-06-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmanagement',
            name='date_approved',
            field=models.DateField(blank=True, null=True),
        ),
    ]
