# Generated by Django 5.2.3 on 2025-06-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_listofpriority_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofpriority',
            name='category',
            field=models.CharField(choices=[('trainDev', 'Training and Development'), ('transport', 'Travel & Transportation'), ('communication', 'Communication & Utilities'), ('office', 'Office Operations & Supplies'), ('services', 'Services & Maintenance'), ('medical', 'Medical & Food Supplies'), ('misc', 'Miscellaneous')], default='misc', max_length=30),
        ),
        migrations.AlterField(
            model_name='school',
            name='schoolId',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
