# Generated by Django 5.2 on 2025-07-08 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_requestmanagement_previous_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestmanagement',
            name='previous_request',
        ),
    ]
