# Generated by Django 5.2 on 2025-09-30 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_enhance_otp_security'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account_locked_until',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_otp_request_ip',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_otp_request_user_agent',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_attempts_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_last_attempt_at',
        ),
    ]
