# Generated by Django 5.2 on 2025-07-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_notification_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='legislativeDistrict',
            field=models.CharField(choices=[('1st District', '1st District'), ('2nd District', '2nd District')], max_length=100),
        ),
    ]
