# Generated by Django 5.2.3 on 2025-06-18 16:52

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_requirement_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='RequestManagement',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_month', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending'), ('inliquidated', 'Inliquidated')], default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LiquidationManagement',
            fields=[
                ('LiquidationID', models.CharField(default=api.models.generate_liquidation_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('comment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(choices=[('ongoing', 'Ongoing'), ('resubmit', 'Resubmit')], max_length=20)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidations', to='api.requestmanagement')),
            ],
        ),
        migrations.CreateModel(
            name='RequestPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.listofpriority')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.requestmanagement')),
            ],
            options={
                'unique_together': {('request', 'priority')},
            },
        ),
        migrations.AddField(
            model_name='requestmanagement',
            name='priorities',
            field=models.ManyToManyField(related_name='requests', through='api.RequestPriority', to='api.listofpriority'),
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
