# Generated by Django 5.1.7 on 2025-07-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_notification_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidationdocument',
            name='is_approved',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
