# Generated by Django 5.2.3 on 2025-06-29 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='max_budget',
            new_name='max_budgett',
        ),
    ]
