# Generated by Django 5.1.7 on 2025-06-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_school_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listofpriority',
            old_name='requirement',
            new_name='requirements',
        ),
        migrations.AddField(
            model_name='listofpriority',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
