# Generated by Django 5.2.3 on 2025-06-13 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_profile_picture_user_role_user_school_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('requirementID', models.AutoField(primary_key=True, serialize=False)),
                ('requirementTitle', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('schoolId', models.CharField(max_length=50, unique=True)),
                ('schoolName', models.CharField(max_length=255)),
                ('municipality', models.CharField(max_length=100)),
                ('legislativeDistrict', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='listofPriority',
            fields=[
                ('LOPID', models.AutoField(primary_key=True, serialize=False)),
                ('expenseTitle', models.CharField(max_length=255)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priorities', to='api.requirement')),
            ],
        ),
    ]
