# Generated by Django 5.2.3 on 2025-06-24 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_requestmanagement_date_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquidationmanagement',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='liquidationmanagement',
            name='reviewed_by',
        ),
        migrations.AddField(
            model_name='liquidationmanagement',
            name='date_districtApproved',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liquidationmanagement',
            name='date_liquidated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestmanagement',
            name='date_downloaded',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestmanagement',
            name='rejection_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestmanagement',
            name='rejection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='liquidationmanagement',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review_district', 'Under Review (District)'), ('under_review_division', 'Under Review (Division)'), ('resubmit', 'Needs Revision'), ('approved_district', 'Approved by District'), ('liquidated', 'Liquidated')], default='draft', max_length=30),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_title', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, null=True)),
                ('notification_date', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
