# Generated by Django 5.2.3 on 2025-06-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=12),
            preserve_default=False,
        ),
    ]
