# Generated by Django 5.2 on 2025-07-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_username_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_change_required',
            field=models.BooleanField(default=True),
        ),
    ]
