# Generated by Django 5.1.7 on 2025-06-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_requestmanagement_request_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
