# Generated by Django 5.2.3 on 2025-07-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_notification_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestmanagement',
            name='date_downloaded',
        ),
        migrations.AddField(
            model_name='requestmanagement',
            name='downloaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
