# Generated by Django 5.2.3 on 2025-06-20 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_requirements_listofpriority_requirementss_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listofpriority',
            old_name='requirementss',
            new_name='requirements',
        ),
    ]
