# Generated by Django 5.2 on 2025-07-08 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_password_change_required'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='requestmanagement',
            name='is_resubmission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requestmanagement',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.requestmanagement'),
        ),
    ]
