# Generated by Django 5.2 on 2025-07-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_school_legislativedistrict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidatorassignment',
            name='district',
            field=models.CharField(choices=[('1st District', '1st District'), ('2nd District', '2nd District')], default='all', max_length=100),
        ),
    ]
