# Generated by Django 5.1.7 on 2025-07-09 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_password_change_required'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
