# Generated by Django 5.2.3 on 2025-06-21 03:47

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_requirementss_listofpriority_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidationmanagement',
            name='LiquidationID',
            field=models.CharField(default=api.models.generate_liquidation_id, editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='requestmanagement',
            name='request_id',
            field=models.CharField(default=api.models.generate_request_id, editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
