# Generated by Django 5.2.3 on 2025-06-19 09:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_sex_requestmanagement_liquidationmanagement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquidationmanagement',
            name='state',
        ),
        migrations.RemoveField(
            model_name='listofpriority',
            name='requirement',
        ),
        migrations.AddField(
            model_name='liquidationmanagement',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liquidationmanagement',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_liquidations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='liquidationmanagement',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('resubmit', 'Resubmit'), ('completed', 'Completed')], default='ongoing', max_length=20),
        ),
        migrations.AlterField(
            model_name='liquidationmanagement',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='liquidation', to='api.requestmanagement'),
        ),
        migrations.AlterField(
            model_name='requestmanagement',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending'), ('unliquidated', 'Unliquidated')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='PriorityRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priority_reqs', to='api.listofpriority')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priority_reqs', to='api.requirement')),
            ],
            options={
                'unique_together': {('priority', 'requirement')},
            },
        ),
        migrations.AddField(
            model_name='listofpriority',
            name='requirements',
            field=models.ManyToManyField(related_name='priority_requirements', through='api.PriorityRequirement', to='api.requirement'),
        ),
        migrations.CreateModel(
            name='LiquidationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='liquidation_documents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('reviewer_comment', models.TextField(blank=True, null=True)),
                ('liquidation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.liquidationmanagement')),
                ('request_priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.requestpriority')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.requirement')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('liquidation', 'request_priority', 'requirement')},
            },
        ),
    ]
