# Generated by Django 5.2.3 on 2025-07-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_requestmanagement_date_downloaded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidationmanagement',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
