# Generated by Django 5.2 on 2025-06-22 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_liquidationmanagement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidationmanagement',
            name='reviewed_at_district',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liquidationmanagement',
            name='reviewed_at_division',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liquidationmanagement',
            name='reviewed_by_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district_reviewed_liquidations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='liquidationmanagement',
            name='reviewed_by_division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='division_reviewed_liquidations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='liquidationmanagement',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review_district', 'Under Review (District)'), ('under_review_division', 'Under Review (Division)'), ('resubmit', 'Needs Revision'), ('approved_district', 'Approved by District'), ('approved_division', 'Approved by Division'), ('approved', 'Fully Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=30),
        ),
    ]
