# Generated by Django 5.2.3 on 2025-06-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_requirement_school_listofpriority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listofpriority',
            name='requirement',
        ),
        migrations.AddField(
            model_name='listofpriority',
            name='requirement',
            field=models.ManyToManyField(related_name='priorities', to='api.requirement'),
        ),
    ]
