# Generated by Django 5.2 on 2025-07-09 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_requestmanagement_previous_request'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('role', 'school')},
        ),
    ]
