# Generated by Django 5.2.3 on 2025-06-29 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_max_budget_school_max_budgett'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='max_budgett',
            new_name='max_budget',
        ),
    ]
