# Generated by Django 5.2 on 2025-07-08 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestmanagement',
            name='is_resubmission',
        ),
        migrations.RemoveField(
            model_name='requestmanagement',
            name='previous_version',
        ),
    ]
