# Generated by Django 5.2.3 on 2025-07-02 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_liquidationmanagement_submitted_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liquidationmanagement',
            old_name='submitted_at',
            new_name='downloaded_at',
        ),
    ]
