# Generated by Django 5.2 on 2025-07-04 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_liquidatorassignment_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school_district',
            field=models.CharField(blank=True, help_text='District assignment (only for district administrative assistants)', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='LiquidatorAssignment',
        ),
    ]
