# Generated by Django 5.2.3 on 2025-06-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_liquidatorassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidatorassignment',
            name='district',
            field=models.CharField(choices=[('all', 'All District'), ('1st', '1st District'), ('2nd', '2nd District')], default='all', max_length=100),
        ),
    ]
