# Generated by Django 5.2.6 on 2025-09-18 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_generatedpdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_path', models.CharField(help_text='Base directory chosen by admin', max_length=1024)),
                ('archive_path', models.CharField(blank=True, help_text='Path to produced archive', max_length=1024)),
                ('format', models.CharField(choices=[('json', 'JSON'), ('sql', 'SQL'), ('csv', 'CSV')], default='json', max_length=20)),
                ('include_media', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file_size', models.BigIntegerField(blank=True, help_text='Size in bytes of the main archive', null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
