# Generated by Django 5.2 on 2025-10-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_user_date_of_birth_remove_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_change_reason',
            field=models.CharField(choices=[('new_user', 'New User Setup'), ('admin_reset', 'Admin Password Reset'), ('self_reset', 'Self-Initiated Reset')], default='new_user', help_text='Reason why password change is required', max_length=20),
        ),
    ]
