# Generated by Django 5.1.7 on 2025-06-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_listofpriority_requirement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='description',
        ),
        migrations.AddField(
            model_name='requirement',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
    ]
