# Generated by Django 5.2.3 on 2025-09-27 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_generatedpdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalliquidationmanagement',
            name='reviewed_at_accountant',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalliquidationmanagement',
            name='reviewed_by_accountant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='liquidationdocument',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liquidationdocument',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='liquidationdocument',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resubmitted', 'Resubmitted')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='liquidationmanagement',
            name='reviewed_at_accountant',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liquidationmanagement',
            name='reviewed_by_accountant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accountant_reviewed_liquidations', to=settings.AUTH_USER_MODEL),
        ),
    ]
