# Generated by Django 5.2.3 on 2025-06-27 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_liquidatorassignment_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidationPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('liquidation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidation_priorities', to='api.liquidationmanagement')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.listofpriority')),
            ],
            options={
                'unique_together': {('liquidation', 'priority')},
            },
        ),
    ]
