# Generated by Django 5.2 on 2025-10-14 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_password_change_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_change_reason',
        ),
    ]
