# Generated by Django 5.2.3 on 2025-07-02 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_submitted_at_liquidationmanagement_downloaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquidationmanagement',
            name='downloaded_at',
        ),
    ]
