# Generated by Django 5.2 on 2025-09-19 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_backup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backup',
            name='archive_path',
        ),
        migrations.RemoveField(
            model_name='backup',
            name='base_path',
        ),
    ]
