# Generated by Django 5.2 on 2025-09-22 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_backup_archive_path_remove_backup_base_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('archive', 'Archive'), ('restore', 'Restore'), ('login', 'Login'), ('logout', 'Logout'), ('approve', 'Approve'), ('reject', 'Reject'), ('submit', 'Submit'), ('download', 'Download'), ('backup', 'Backup'), ('restore', 'Restore'), ('password_change', 'Password Change')], max_length=20)),
                ('module', models.CharField(choices=[('user', 'User Management'), ('school', 'School Management'), ('request', 'Request Management'), ('liquidation', 'Liquidation Management'), ('priority', 'Priority Management'), ('requirement', 'Requirement Management'), ('district', 'District Management'), ('system', 'System Operations'), ('auth', 'Authentication')], max_length=20)),
                ('object_id', models.CharField(blank=True, max_length=100, null=True)),
                ('object_type', models.CharField(blank=True, max_length=100, null=True)),
                ('object_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='api_auditlo_user_id_8f69e8_idx'), models.Index(fields=['module', 'action'], name='api_auditlo_module_57db4a_idx'), models.Index(fields=['object_type', 'object_id'], name='api_auditlo_object__e7bdeb_idx')],
            },
        ),
    ]
