# Generated by Django 5.2.3 on 2025-06-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_liquidationpriority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestmanagement',
            name='request_month',
        ),
        migrations.AddField(
            model_name='liquidationmanagement',
            name='refund',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='requestmanagement',
            name='request_monthyear',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='last_liquidated_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='last_liquidated_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listofpriority',
            name='category',
            field=models.CharField(choices=[('travel', 'Travel Expenses'), ('training', 'Training Expenses'), ('scholarship', 'Scholarship Grants/Expenses'), ('supplies', 'Office Supplies & Materials Expenses'), ('utilities', 'Utilities Expenses'), ('communication', 'Communication Expenses'), ('awards', 'Awards/Rewards/Prizes Expenses'), ('survey', 'Survey, Research, Exploration and Development Expenses'), ('confidential', 'Confidential & Intelligence Expenses'), ('extraordinary', 'Extraordinary and Miscellaneous Expenses'), ('professional', 'Professional Service Expenses'), ('services', 'General Services'), ('maintenance', 'Repairs and Maintenance Expenses'), ('financial_assistance', 'Financial Assistance/Subsidy Expenses'), ('taxes', 'Taxes, Duties and Licenses Expenses'), ('labor', 'Labor and Wages Expenses'), ('other_maintenance', 'Other Maintenance and Operating Expenses'), ('financial', 'Financial Expenses'), ('non_cash', 'Non-cash Expenses'), ('losses', 'Losses')], default='other_maintenance', max_length=30),
        ),
        migrations.AlterField(
            model_name='requestmanagement',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending'), ('downloaded', 'Downloaded'), ('advanced', 'Advanced')], default='pending', max_length=20),
        ),
    ]
