# Generated by Django 5.2.3 on 2025-06-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_requestmanagement_request_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidationmanagement',
            name='remaining_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
