"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a&-*rs31mdo&jc3@4zu8*sp7wdhp_1#5w4bc@%mx=bb=ohlo1e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Replace with your actual PC IP
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'daphne',  # ASGI server for WebSockets
    'channels',  # WebSocket support
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',  # Add JWT blacklist support
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'api',
    'auditlog',
    'django_celery_results',  # For storing Celery task results
    'django_celery_beat',     # For scheduled tasks
    'simple_history',  # For tracking model history
]

# Optional: Configure auditlog settings
# Set to True to track all models automatically
AUDITLOG_INCLUDE_ALL_MODELS = False
AUDITLOG_EXCLUDE_TRACKING_MODELS = ()  # Exclude specific models if needed
# JWT Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# JWT Authentication with blacklist
REST_FRAMEWORK['DEFAULT_AUTHENTICATION_CLASSES'] = (
    'rest_framework_simplejwt.authentication.JWTAuthentication',
)
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'api.middleware.AllowIframeForMediaMiddleware',
    'api.middleware.AuditMiddleware',  # Custom middleware for audit logging
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'backend.urls'
CORS_ALLOWED_ORIGINS = ["http://localhost:5173",
                        "http://192.168.1.147:5173", "http://192.168.1.111:5173", "http://192.168.1.232:5173", "http://192.168.0.231:5173", "http://172.20.10.2:5173", "http://172.20.10.7:5173"]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]
CORS_ALLOW_CREDENTIALS = True  # This is the critical missing setting

FRONTEND_LOGIN_URL = 'http://localhost:5173/login'

# Session and CSRF cookie settings for development
# For development (HTTP), use 'Lax' and False
# For production (HTTPS), use 'None' and True
SESSION_COOKIE_SAMESITE = 'Lax'  # Changed from 'None' for HTTP compatibility
SESSION_COOKIE_SECURE = False    # Changed from True for HTTP compatibility
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7  # 7 days (same as refresh token lifetime)
CSRF_COOKIE_SAMESITE = 'Lax'     # Changed from 'None' for HTTP compatibility
CSRF_COOKIE_SECURE = False       # Changed from True for HTTP compatibility
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'proj_backend',
                         'api', 'templates', 'emails'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'
ASGI_APPLICATION = 'backend.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'db_liquidation_management_system',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}


AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # This is the default backend
    # Add any additional backends here if you're using them
]
AUTH_USER_MODEL = 'api.User'
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=900),  # Reduced from 50 minutes
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),     # Reduced from 1 day
    'ROTATE_REFRESH_TOKENS': True,                   # Enable token rotation
    'BLACKLIST_AFTER_ROTATION': True,                # Enable blacklisting
    'UPDATE_LAST_LOGIN': True,                       # Track last login

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': 'liquidation-management-system',       # Add issuer
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=7),
    
    # Add blacklist settings
    'BLACKLIST_TOKEN_CHECKS': [
        'rest_framework_simplejwt.token_blacklist.blacklist_checks.check_blacklist',
    ],
}

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# settings.py
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'riverajanlester.st.maria@gmail.com'  # Your email address

EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', 'tght ymcl oqus vjyw')
# Default sender email
DEFAULT_FROM_EMAIL = 'DepEd LUSDO <noreply@deped.gov.ph>'

# Liquidation Reminder Configuration
LIQUIDATION_REMINDER_DAYS = [15, 5, 1]  # 15 days, 5 days, and 1 day before due date
LIQUIDATION_DEADLINE_DAYS = 30
EMAIL_RATE_LIMIT_PER_USER_PER_DAY = 5  # Max emails per user per day
# Celery Configuration
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'django_celery_results.backends:DatabaseBackend'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes
CELERY_TASK_SOFT_TIME_LIMIT = 60  # 1 minute
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000


CELERY_BEAT_SCHEDULE = {
    'monthly-audit-precise': {
        'task': 'api.tasks.monthly_request_status_audit',
        # 1st of month at 2:00 AM
        'schedule': crontab(hour=2, minute=0, day_of_month=1),
    },
    'check-liquidation-reminders-daily': {
        'task': 'api.tasks.check_liquidation_reminders',
        # Run every 2 minutes for testing
        'schedule': crontab(minute='*/2'),
    },
    'update-remaining-days-daily': {
        'task': 'api.tasks.update_liquidation_remaining_days',
        # Daily at midnight
        'schedule': crontab(hour=0, minute=0),
    },
    'process-advanced-requests-daily': {
        'task': 'api.tasks.process_advanced_requests',
        # Run every 2 minutes for testing
        'schedule': crontab(minute='*/2'),
    },
}


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'api': {  # Replace with your actual app name
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}
# Backup/Restore settings
# Server-managed defaults to avoid trusting client-supplied filesystem paths
BACKUP_SETTINGS = {
    'DEFAULT_BACKUP_DIR': os.path.join(BASE_DIR, 'Backups'),
    'MAX_BACKUP_AGE_DAYS': 30,
    'ALLOW_CUSTOM_PATHS': False,
    'COMPRESSION_LEVEL': 6,
}

# Channels configuration for WebSocket support
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}
